### PR TITLE
use computed toolbar `classes` instead of data `rootClasses`

### LINKED ISSUE #13: `toolbar` classes not being updated when using hot module replacement
If I make a change to one of the props in `mdc-toolbar`, for example.

`<mdc-toolbar :waterfall="true" ...>` and then run my project. After making this change: `<mdc-toolbar :waterfall="false" ...>`, and saving the change, forcing recompilation, `rootClasses` and the element's class do not get updated

### PR DESCRIPTION
**Pull request by griest024**
- add `align-center` to `mdc-toolbar-section`
- toolbar elements reflect changes in bound props

fixes #13

### CODE REVIEW

**Comment by griest024** [comment]
@stasson if you want an example of when this might be useful, look at `Doc.vue` in #20. It makes sense to be able to switch between multiple type of components dynamically to showcase every component.

**Comment by griest024** [comment]
@stasson have you considered this PR yet?

**Comment by stasson** [comment]
@griest024  

Sorry, I got busy understanding/fixing my build env & some webpack issues, creating a working unpkg distribution, cleaning up the preview site...

I just had a quick look at the code and there are some good points (flexible default, ...). 
I'm still uneasy with the need for dynamic behaviour though (data vs computed). For showcasing, there are other way outside the component (aka same way you did on drawer...) 
I'll try to find more time to go through it this week and settle this PR.

**Comment by griest024** [comment]
@stasson The only reason that I was able to handle the drawer in that way is because there were actually separate components. 

If you look at the code, `mdc-drawer-header` actually relies on the ability to dynamically change the classes on the component: `:type="drawerType"`, which is what this PR implements for `mdc-toolbar`.

This is a dealbreaker. If you can't see why this is a good thing for the project (increases user freedom), then clearly our visions for the project do not align.

**Comment by stasson** [comment]
@griest024 

Just came back after a busy 3 days session @ work and I couldn't help notice You closed this issue ? I'm surprised. I was planning to investigate this more so we can settle our differences on this one. Was I too long to answer and you decided to drop it ?

Let me know where we stand. Thxs.

**Comment by griest024** [comment]
@stasson after much consideration, I have decided to no longer contribute to this repository.

**Comment by stasson** [comment]
@griest024 

Ok, I'm sorry sorry to hear that. Thanks for your help and insights on the project.

**Pull request closed without merging**
