### PR TITLE
feat(textfield): add slots before and after textfield

### LINKED ISSUE #166: Ability to have button beside textbox?
I was using MDC-Web directly and had the following markup:

>     <div class="mdc-text-field" data-mdc-auto-init="MDCTextField">
>         <input id="search" type="textarea" class="mdc-text-field__input" />
>         <label for="search" class="mdc-text-field__label">Search</label>
>         <div class="mdc-text-field__bottom-line"></div>
>     </div>
>     <button type="submit" class="mdc-button mdc-button--raised mdc-ripple-surface" data-mdc-auto-init="MDCRipple">Search</button>
> 

I've started converting the site over to utilize the adapter and changed the code to:

`<mdc-textfield v-model="search" label="Search" /><mdc-button raised>Search</mdc-button>`

What would I need to do in order to keep the textfield and the button on the same line?

I can utilize the mdc-layout-grid, but it adds a lot of markup and the alignment is off:

`<mdc-layout-grid>
    <mdc-layout-cell><mdc-textfield v-model="search" label="Search" /></mdc-layout-cell>
    <mdc-layout-cell align="middle"><mdc-button raised>Search</mdc-button></mdc-layout-cell>
</mdc-layout-grid>`

Any suggestions to what I can do differently?

### PR DESCRIPTION
**Pull request by griest024**
closes #166

### CODE REVIEW

**Comment by rustemgareev** [comment]
I would call these slots "start" and "end", according to [CSS logical properties](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties): "start" and "end" for left and right respectively, "before" / "after" for top and bottom.

**Comment by griest024** [comment]
@rustemgareev noted. Thank you.

**Comment by griest024** [comment]
@stasson Is there any case where we would want slots inside the `mdc-textfield-wrapper`?

**Comment by stasson** [comment]
@griest024 
actually yes you probably need start/end slots to implement <https://material.io/components/web/catalog/input-controls/text-fields/#leading-and-trailing-icons>

**Comment by griest024** [comment]
Do you prefer the slot implementation or could we get away with using props?

**Comment by griest024** [comment]
@stasson I'm closing this for now. I'll implement leading and trailing icons in a different PR after #175 is merged.

**Pull request closed without merging**
